# Variables
IMAGE_NAME ?= usabilitydynamics/udx-worker
TAG ?= latest
DOCKER_IMAGE := $(IMAGE_NAME):$(TAG)
CONTAINER_NAME ?= udx-worker-container
USER_WORKER_CONFIG ?= ./tests/configs/worker.yml
DEBUG ?= false
