# Variables
IMAGE_NAME ?= usabilitydynamics/udx-worker
TAG ?= latest
DOCKER_IMAGE := $(IMAGE_NAME):$(TAG)
CONTAINER_NAME ?= udx-worker-container
TEST_WORKER_CONFIG ?= ./tests/configs/worker.yml
VOLUMES ?=
DEBUG ?= false
COMMAND ?=sh
MULTIPLATFORM ?= false
FOLLOW_LOGS ?= false