---
kind: workerConfig
version: udx.io/worker-v1/config
config:
  actors:
    - type: gcp
      creds: "${GCP_CREDS}"
    - type: azure
      creds: "${AZURE_CREDS}"
    - type: aws
      creds: "${AWS_CREDS}"
