---
kind: workerService
version: udx.io/worker-v1/service
services:
  - name: "app_service"
    ignore: "true"
    command: "sh /usr/local/scripts/main.sh"
    autostart: "true"
    autorestart: "false"
    envs:
      - "KEY1=value1"
      - "KEY2=value2"
  - name: "another_service"
    ignore: "true"
    command: "sh /usr/local/scripts/main.sh"
    autostart: "true"
    autorestart: "true"
    envs: []
