[program:${process_name}]
# Process command and restart settings
command=${command}
autostart=${autostart}
autorestart=${autorestart}
startretries=3

# Logging settings
stdout_logfile=/var/log/supervisor/${process_name}.out.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
stderr_logfile=/var/log/supervisor/${process_name}.err.log
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=10

# Environment
environment=${envs}