[program:${process_name}]
# Process command and restart settings
command=/usr/bin/tini -s -g -- ${command}
autostart=${autostart}
autorestart=${autorestart}
startretries=3
startsecs=10

# Signal handling
stopwaitsecs=15
stopasgroup=true
killasgroup=true
stopsignal=TERM

# Logging settings
stdout_logfile=/var/log/supervisor/${process_name}.out.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile=/var/log/supervisor/${process_name}.err.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=3

# Environment
environment=${envs}