[program:${process_name}]
# Process command and restart settings
command=${command}
autostart=${autostart}
autorestart=${autorestart}
startretries=${startretries}
startsecs=1          # Consider process started if it runs for at least 1 second

# Logging settings
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2  
stderr_logfile_maxbytes=0

# Environment
environment=${envs}