[program:${process_name}]
command=${command}
autostart=${autostart}
autorestart=${autorestart}
stderr_logfile=/var/log/supervisor/${process_name}.err.log
stdout_logfile=/var/log/supervisor/${process_name}.out.log
environment=${envs}