#!/bin/bash

# shellcheck source=${WORKER_LIB_DIR}/utils.sh disable=SC1091
source "${WORKER_LIB_DIR}/utils.sh"

# Environment file location
WORKER_ENV_FILE="/etc/worker/environment"

# Generate environment file with regular variables
generate_env_file() {
    local config
    config=$(load_and_parse_config)
    
    if [ -z "$config" ]; then
        log_error "Environment" "Failed to load configuration"
        return 1
    fi

    log_info "Environment" "Loading environment variables from configuration"
    
    # Create the environment file
    touch "$WORKER_ENV_FILE"
    
    # Process each environment variable
    while IFS= read -r entry; do
        # Extract key and value using string manipulation instead of regex
        if [[ $entry == export* ]]; then
            # Remove 'export ' prefix
            local kv_pair=${entry#export }
            # Extract key (everything before =)
            local key=${kv_pair%%=*}
            # Extract value (everything after = and remove quotes)
            local value=${kv_pair#*=}
            value=${value//\"/}
            value=${value#\"}
            value=${value%\"}
            
            # Check if the environment variable already exists
            if [[ -z "${!key+x}" ]]; then
                # Variable doesn't exist in environment, add it from config
                echo "export $key=\"$value\"" >> "$WORKER_ENV_FILE"
            else
                # Variable exists in environment, use that value instead
                local env_value="${!key}"
                echo "export $key=\"$env_value\"" >> "$WORKER_ENV_FILE"
                log_info "Environment" "Detected [$key] in container environment - using runtime value instead of config value"
            fi
        fi
    done < <(echo "$config" | yq eval '.config.env | to_entries | .[] | "export " + .key + "=\"" + .value + "\""' -)
}

# Append resolved secrets to environment file
append_resolved_secrets() {
    local secrets_json="$1"
    local has_failures=false
    
    if [ -z "$secrets_json" ]; then
        log_error "Environment" "No secrets provided"
        return 1
    fi
    
    # Create a temporary file for resolved secrets
    local temp_file
    temp_file=$(mktemp)
    
    {
        echo ""
        echo "# Resolved Secrets"
        echo "# Generated on $(date)"
        echo "# DO NOT EDIT THIS FILE DIRECTLY"
        echo
    } > "$temp_file"
    
    # Process each secret and resolve it
    while IFS= read -r secret; do
        local name value
        name=$(echo "$secret" | jq -r '.key')
        
        # Create config JSON for resolve_secret_by_name
        local config_json
        config_json="{ \"config\": { \"secrets\": { \"$name\": $(echo "$secret" | jq '.value') } } }"
        
        # Resolve the secret
        if ! value=$(resolve_secret_by_name "$name" "$config_json") || [[ -z "$value" ]]; then
            log_error "Environment" "Failed to resolve secret for $name"
            has_failures=true
        else
            echo "export $name=\"$value\"" >> "$temp_file"
            log_success "Environment" "Resolved secret for $name"
        fi
    done < <(echo "$secrets_json" | jq -c 'to_entries[]')
    
    # If any secret failed to resolve, error out
    if [[ "$has_failures" == "true" ]]; then
        log_error "Environment" "Failed to resolve one or more secrets"
        rm -f "$temp_file"
        return 1
    fi
    
    # If we get here, all secrets resolved successfully
    cat "$temp_file" >> "$WORKER_ENV_FILE"
    log_success "Environment" "Added all resolved secrets to environment file"
    rm -f "$temp_file"
}

# Load environment variables and secrets
load_environment() {
    if [ -f "$WORKER_ENV_FILE" ]; then
        # shellcheck source=/dev/null
        source "$WORKER_ENV_FILE"
    else
        log_warn "Environment" "Environment file not found, generating..."
        generate_env_file
        # shellcheck source=/dev/null
        source "$WORKER_ENV_FILE"
    fi
}

# Format environment variables as JSON or text
format_env_vars() {
    local vars=$1
    local format=${2:-text}
    
    case $format in
        json)
            # Convert to JSON
            local json="{"
            while IFS= read -r line; do
                if [[ $line =~ ^export[[:space:]]+([^=]+)=\"([^\"]*)\" ]]; then
                    if [ -n "$json" ] && [ "$json" != "{" ]; then
                        json="$json,"
                    fi
                    key=${BASH_REMATCH[1]}
                    value=${BASH_REMATCH[2]}
                    json="$json\"$key\":\"$value\""
                fi
            done <<< "$vars"
            json="$json}"
            echo "$json" | jq .
            ;;
        text)
            echo "${vars#export }" | tr -d '\"'
            ;;
        *)
            log_error "Environment" "Unknown format: $format"
            return 1
            ;;
    esac
}

# Initialize environment
init_environment() {
    generate_env_file
    generate_secrets_file
    load_environment
    load_secrets
}

# Update environment when config changes
update_environment() {
    generate_env_file
    generate_secrets_file
    load_environment
    load_secrets
}

# Get environment variable value
get_env_value() {
    local var_name="$1"
    
    if [ -z "$var_name" ]; then
        log_error "Environment" "Variable name not provided"
        return 1
    fi
    
    if [ -f "$WORKER_ENV_FILE" ]; then
        grep "^export $var_name=" "$WORKER_ENV_FILE" | cut -d'=' -f2- | tr -d '"'
    elif [ -f "$WORKER_SECRETS_FILE" ]; then
        grep "^export $var_name=" "$WORKER_SECRETS_FILE" | cut -d'=' -f2- | tr -d '"'
    else
        log_error "Environment" "Neither environment nor secrets file exists"
        return 1
    fi
}

# List all environment variables
list_env_vars() {
    local show_secrets="$1"
    local env_vars=""
    local secret_vars=""
    
    if [ -f "$WORKER_ENV_FILE" ]; then
        env_vars=$(grep "^export" "$WORKER_ENV_FILE" | cut -d'=' -f1 | cut -d' ' -f2)
    fi
    
    if [ "$show_secrets" = "true" ] && [ -f "$WORKER_SECRETS_FILE" ]; then
        secret_vars=$(grep "^export" "$WORKER_SECRETS_FILE" | cut -d'=' -f1 | cut -d' ' -f2)
    fi
    
    if [ -n "$env_vars" ]; then
        echo "Environment Variables:"
        echo "$env_vars"
    fi
    
    if [ -n "$secret_vars" ]; then
        echo
        echo "Secret Variables:"
        echo "$secret_vars"
    fi
}