#!/bin/bash

# shellcheck source=${WORKER_LIB_DIR}/utils.sh disable=SC1091
source "${WORKER_LIB_DIR}/utils.sh"

# Environment file location
WORKER_ENV_FILE="/etc/worker/environment"
WORKER_SECRETS_FILE="/etc/worker/secrets"

# Generate environment file from worker.yaml
generate_env_file() {
    local config
    config=$(load_and_parse_config)
    
    if [ -z "$config" ]; then
        log_error "Environment" "Failed to load configuration"
        return 1
    fi
    
    # Extract and evaluate environment variables
    {
        echo "# Worker Environment Variables"
        echo "# Generated on $(date)"
        echo "# DO NOT EDIT THIS FILE DIRECTLY"
        echo
        
        # Extract environment variables
        echo "$config" | yq eval '.config.env | to_entries | .[] | "export " + .key + "=\"" + .value + "\""' -
    } > "$WORKER_ENV_FILE"
    
    # File permissions are set during build
}

# Generate secrets file from worker.yaml
generate_secrets_file() {
    local config
    config=$(load_and_parse_config)
    
    if [ -z "$config" ]; then
        log_error "Environment" "Failed to load configuration"
        return 1
    fi
    
    # Extract and evaluate secrets
    {
        echo "# Worker Secrets"
        echo "# Generated on $(date)"
        echo "# DO NOT EDIT THIS FILE DIRECTLY"
        echo "# DO NOT COMMIT THIS FILE"
        echo
        
        # Extract secrets
        echo "$config" | yq eval '.config.secrets | to_entries | .[] | "export " + .key + "=\"" + .value + "\""' -
    } > "$WORKER_SECRETS_FILE"
    
    # File permissions are set during build
}

# Load environment variables
load_environment() {
    if [ -f "$WORKER_ENV_FILE" ]; then
        # shellcheck source=/dev/null
        source "$WORKER_ENV_FILE"
    else
        log_warn "Environment" "Environment file not found, generating..."
        generate_env_file
        # shellcheck source=/dev/null
        source "$WORKER_ENV_FILE"
    fi
}

# Load secrets
load_secrets() {
    if [ -f "$WORKER_SECRETS_FILE" ]; then
        # shellcheck source=/dev/null
        source "$WORKER_SECRETS_FILE"
    else
        log_warn "Environment" "Secrets file not found, generating..."
        generate_secrets_file
        # shellcheck source=/dev/null
        source "$WORKER_SECRETS_FILE"
    fi
}

# Format environment variables as JSON or text
format_env_vars() {
    local vars=$1
    local format=${2:-text}
    
    case $format in
        json)
            # Convert to JSON
            local json="{"
            while IFS= read -r line; do
                if [[ $line =~ ^export[[:space:]]+([^=]+)=\"([^\"]*)\" ]]; then
                    if [ -n "$json" ] && [ "$json" != "{" ]; then
                        json="$json,"
                    fi
                    key=${BASH_REMATCH[1]}
                    value=${BASH_REMATCH[2]}
                    json="$json\"$key\":\"$value\""
                fi
            done <<< "$vars"
            json="$json}"
            echo "$json" | jq .
            ;;
        text)
            echo "${vars#export }" | tr -d '\"'
            ;;
        *)
            log_error "Environment" "Unknown format: $format"
            return 1
            ;;
    esac
}

# Initialize environment
init_environment() {
    generate_env_file
    generate_secrets_file
    load_environment
    load_secrets
}

# Update environment when config changes
update_environment() {
    generate_env_file
    generate_secrets_file
    load_environment
    load_secrets
}

# Get environment variable value
get_env_value() {
    local var_name="$1"
    
    if [ -z "$var_name" ]; then
        log_error "Environment" "Variable name not provided"
        return 1
    fi
    
    if [ -f "$WORKER_ENV_FILE" ]; then
        grep "^export $var_name=" "$WORKER_ENV_FILE" | cut -d'=' -f2- | tr -d '"'
    elif [ -f "$WORKER_SECRETS_FILE" ]; then
        grep "^export $var_name=" "$WORKER_SECRETS_FILE" | cut -d'=' -f2- | tr -d '"'
    else
        log_error "Environment" "Neither environment nor secrets file exists"
        return 1
    fi
}

# List all environment variables
list_env_vars() {
    local show_secrets="$1"
    local env_vars=""
    local secret_vars=""
    
    if [ -f "$WORKER_ENV_FILE" ]; then
        env_vars=$(grep "^export" "$WORKER_ENV_FILE" | cut -d'=' -f1 | cut -d' ' -f2)
    fi
    
    if [ "$show_secrets" = "true" ] && [ -f "$WORKER_SECRETS_FILE" ]; then
        secret_vars=$(grep "^export" "$WORKER_SECRETS_FILE" | cut -d'=' -f1 | cut -d' ' -f2)
    fi
    
    if [ -n "$env_vars" ]; then
        echo "Environment Variables:"
        echo "$env_vars"
    fi
    
    if [ -n "$secret_vars" ]; then
        echo
        echo "Secret Variables:"
        echo "$secret_vars"
    fi
}