name: Release

on:
  push:
    # branches:
    #   - "latest"

jobs:
  docker-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.0
        with:
          versionSpec: "6.0.0"

      - name: Clear GitVersion Cache
        run: rm -rf .git/gitversion_cache

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.0.0
        with:
          useConfigFile: true
          configFilePath: ci/git-version.yml

      - name: Generate changelog
        id: changelog
        run: |
          git log $(git describe --tags --abbrev=0)..HEAD -- . \
            --pretty=format:"- %s" > changelog.txt
          CHANGELOG=$(cat changelog.txt | jq -sRr @uri)
          echo "changelog<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Multi-arch build and push to Docker Hub
        id: build-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            usabilitydynamics/udx-worker:${{ steps.gitversion.outputs.semVer }}
            usabilitydynamics/udx-worker:latest

      - name: Generate SBOM
        id: generate-sbom
        run: |
          export TRIVY_DISABLE_VEX_NOTICE=true
          trivy image --format spdx-json --output sbom.json usabilitydynamics/udx-worker:${{ steps.gitversion.outputs.semVer }} 2>/dev/null

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.7.0

      - name: Sign Docker image with Cosign
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        run: |
          cosign sign \
            --key env://COSIGN_PRIVATE_KEY \
            usabilitydynamics/udx-worker:${{ steps.gitversion.outputs.semVer }}

      - name: Sign SBOM with Cosign
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        run: |
          cosign attest \
            --key env://COSIGN_PRIVATE_KEY \
            --type sbom \
            --predicate sbom.json \
            usabilitydynamics/udx-worker:${{ steps.gitversion.outputs.semVer }}

      - name: Log out from Docker Hub
        run: docker logout

    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
      changelog: ${{ steps.changelog.outputs.changelog }}

  github-release:
    runs-on: ubuntu-latest
    needs: docker-release
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git for pushing
        run: |
          git config --global user.email "worker@udx.io"
          git config --global user.name "UDX Worker"

      - name: Create GitHub Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git tag ${{ needs.docker-release.outputs.semVer }}
          git push origin ${{ needs.docker-release.outputs.semVer }}

      - name: Download SBOM Artifact
        uses: actions/download-artifact@v4
        with:
          name: sbom

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.docker-release.outputs.semVer }}
          body: |
            Release version ${{ needs.docker-release.outputs.semVer }}.
            [View on Docker Hub](https://hub.docker.com/r/usabilitydynamics/udx-worker/tags?page=1&ordering=last_updated).
            ${{ needs.docker-release.outputs.changelog }}
          draft: false
          prerelease: false
          files: sbom.json
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
