---
name: Release Test Workflow

on:
  push:
    branches-ignore: latest

jobs:
  release-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clear GitVersion Cache
        run: rm -rf .git/gitversion_cache

      - name: Fetch All Tags
        run: git fetch --tags --force

      - name: Set up GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.0
        with:
          versionSpec: "5.12.0"

      - name: Determine Version
        id: gitversion
        run: |
          $GITVERSION_PATH/dotnet-gitversion /output json /output buildserver /config ci/git-version.yml
        env:
          GITVERSION_PATH: /opt/hostedtoolcache/GitVersion.Tool/5.12.0
        

      - name: Display GitVersion Output
        run: |
          echo "Full GitVersion output:"
          echo "Version: ${{ steps.gitversion.outputs.semVer }}"
          echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
          echo "MajorMinorPatch: ${{ steps.gitversion.outputs.majorMinorPatch }}"
          echo "InformationalVersion: ${{ steps.gitversion.outputs.informationalVersion }}"

      - name: Debug GitVersion Cache Directory
        run: ls -la .git/gitversion_cache/
